/**
 * Typed data access for every dashboard screen.
 *
 * One module rather than per-screen fetchers so that query keys are declared
 * in one place: a key that differs by a character between a read and the
 * invalidation after a write is a screen that silently shows stale data, and
 * that bug is invisible until someone notices a number not moving.
 *
 * Response types come from `schema.d.ts`, generated by `make api-types`.
 */
import { apiFetch } from './api';
import type { components } from './schema';
import type { TimeRange } from './uiContext';

type Schemas = components['schemas'];

export type UsageResponse = Schemas['UsageResponse'];
export type BreakdownResponse = Schemas['BreakdownResponse'];
export type TokenDistributionResponse = Schemas['TokenDistributionResponse'];
export type RequestPage = Schemas['RequestPage'];
export type RequestRow = Schemas['RequestRow'];
export type CacheStatsResponse = Schemas['CacheStatsResponse'];
export type RoutingStatsResponse = Schemas['RoutingStatsResponse'];
export type RuleResponse = Schemas['RuleResponse'];
export type BudgetResponse = Schemas['BudgetResponse'];
export type AlertPage = Schemas['AlertPage'];
export type AlertResponse = Schemas['AlertResponse'];
export type RecommendationResponse = Schemas['RecommendationResponse'];
export type BreakEvenResponse = Schemas['BreakEvenResponse'];
export type PromptOptimizationReport = Schemas['PromptOptimizationReport'];
export type CompressResponse = Schemas['CompressResponse'];
export type PlanResponse = Schemas['PlanResponse'];
export type PeerBenchmarkResponse = Schemas['PeerBenchmarkResponse'];
export type ProjectResponse = Schemas['ProjectResponse'];
export type ProxyKeyResponse = Schemas['ProxyKeyResponse'];
export type CreatedProxyKeyResponse = Schemas['CreatedProxyKeyResponse'];
export type KeyResponse = Schemas['KeyResponse'];
export type TestConnectionResponse = Schemas['TestConnectionResponse'];

/** Query keys. Every read and every invalidation goes through these. */
export const keys = {
  usage: (project: string, range: TimeRange) => ['usage', project, range] as const,
  breakdown: (project: string, range: TimeRange, by: string) =>
    ['usage', 'breakdown', project, range, by] as const,
  tokenDistribution: (project: string, range: TimeRange) =>
    ['usage', 'tokens', project, range] as const,
  requests: (project: string, range: TimeRange, decision: string) =>
    ['requests', project, range, decision] as const,
  cacheStats: (project: string, range: TimeRange) => ['cache', 'stats', project, range] as const,
  routingStats: (project: string, range: TimeRange) =>
    ['routing', 'stats', project, range] as const,
  routingRules: (project: string) => ['routing', 'rules', project] as const,
  budgets: (project: string) => ['budgets', project] as const,
  alerts: (project: string, status: string) => ['alerts', project, status] as const,
  recommendations: (project: string) => ['advisor', 'recommendations', project] as const,
  breakeven: (project: string) => ['advisor', 'breakeven', project] as const,
  promptOptimizations: (project: string, range: TimeRange) =>
    ['advisor', 'prompts', project, range] as const,
  plan: () => ['billing', 'plan'] as const,
  benchmark: () => ['benchmark', 'peer'] as const,
  projects: () => ['projects'] as const,
  proxyKeys: (project: string) => ['proxy-keys', project] as const,
  providerKeys: () => ['provider-keys'] as const,
};

function query(params: Record<string, string | number | boolean | undefined>): string {
  const search = new URLSearchParams();
  for (const [key, value] of Object.entries(params)) {
    if (value !== undefined && value !== '') search.set(key, String(value));
  }
  const rendered = search.toString();
  return rendered ? `?${rendered}` : '';
}

// -- Usage / Overview -------------------------------------------------------

export const getUsage = (token: string, projectId: string, range: TimeRange) =>
  apiFetch<UsageResponse>(`/usage${query({ range, project_id: projectId })}`, { token });

export const getBreakdown = (token: string, projectId: string, range: TimeRange, by: string) =>
  apiFetch<BreakdownResponse>(`/usage/breakdown${query({ range, by, project_id: projectId })}`, {
    token,
  });

export const getTokenDistribution = (token: string, projectId: string, range: TimeRange) =>
  apiFetch<TokenDistributionResponse>(
    `/usage/token-distribution${query({ range, project_id: projectId })}`,
    { token },
  );

export const getRequests = (
  token: string,
  projectId: string,
  range: TimeRange,
  decision?: string,
  cursor?: string,
) =>
  apiFetch<RequestPage>(
    `/requests${query({ range, project_id: projectId, decision, cursor, limit: 50 })}`,
    { token },
  );

export const exportCsvUrl = (projectId: string, range: TimeRange) =>
  `/usage/export.csv${query({ range, project_id: projectId })}`;

// -- Cache ------------------------------------------------------------------

export const getCacheStats = (token: string, projectId: string, range: TimeRange) =>
  apiFetch<CacheStatsResponse>(`/cache/stats${query({ range, project_id: projectId })}`, { token });

export const invalidateCache = (token: string, projectId: string) =>
  apiFetch<Schemas['InvalidateResponse']>('/cache/invalidate', {
    method: 'POST',
    token,
    body: { project_id: projectId },
  });

// -- Routing ----------------------------------------------------------------

export const getRoutingStats = (token: string, projectId: string, range: TimeRange) =>
  apiFetch<RoutingStatsResponse>(`/routing/stats${query({ range, project_id: projectId })}`, {
    token,
  });

export const listRoutingRules = (token: string, projectId: string) =>
  apiFetch<RuleResponse[]>(`/routing-rules${query({ project_id: projectId })}`, { token });

export const createRoutingRule = (token: string, body: Schemas['CreateRuleRequest']) =>
  apiFetch<RuleResponse>('/routing-rules', { method: 'POST', token, body });

export const deleteRoutingRule = (token: string, ruleId: string) =>
  apiFetch<void>(`/routing-rules/${ruleId}`, { method: 'DELETE', token });

// -- Budgets ----------------------------------------------------------------

export const listBudgets = (token: string, projectId: string) =>
  apiFetch<BudgetResponse[]>(`/budgets${query({ project_id: projectId })}`, { token });

export const createBudget = (token: string, body: Schemas['CreateBudgetRequest']) =>
  apiFetch<BudgetResponse>('/budgets', { method: 'POST', token, body });

export const updateBudget = (token: string, id: string, body: Schemas['UpdateBudgetRequest']) =>
  apiFetch<BudgetResponse>(`/budgets/${id}`, { method: 'PATCH', token, body });

export const deleteBudget = (token: string, id: string) =>
  apiFetch<void>(`/budgets/${id}`, { method: 'DELETE', token });

// -- Alerts -----------------------------------------------------------------

export const listAlerts = (token: string, projectId: string, status?: string, cursor?: string) =>
  apiFetch<AlertPage>(
    `/alert-events${query({ project_id: projectId, status, cursor, limit: 50 })}`,
    {
      token,
    },
  );

export const resolveAlert = (token: string, id: string, body: Schemas['ResolveAlertRequest']) =>
  apiFetch<AlertResponse>(`/alert-events/${id}/resolve`, { method: 'POST', token, body });

export const killProject = (token: string, projectId: string) =>
  apiFetch<Schemas['KillSwitchResponse']>(`/projects/${projectId}/kill`, { method: 'POST', token });

// -- Advisor ----------------------------------------------------------------

export const listRecommendations = (token: string, projectId: string) =>
  apiFetch<RecommendationResponse[]>(
    `/advisor/recommendations${query({ project_id: projectId })}`,
    { token },
  );

export const setRecommendationStatus = (token: string, id: string, status: string) =>
  apiFetch<RecommendationResponse>(`/advisor/recommendations/${id}/status`, {
    method: 'POST',
    token,
    body: { status },
  });

export const getBreakeven = (token: string, projectId: string) =>
  apiFetch<BreakEvenResponse>(`/advisor/breakeven${query({ project_id: projectId })}`, { token });

export const getPromptOptimizations = (token: string, projectId: string, range: TimeRange) =>
  apiFetch<PromptOptimizationReport>(
    `/advisor/prompt-optimizations${query({ project_id: projectId, range })}`,
    { token },
  );

export const compressPrompt = (token: string, body: unknown) =>
  apiFetch<CompressResponse>('/advisor/compress', { method: 'POST', token, body: { body } });

// -- Billing / benchmark ----------------------------------------------------

export const getPlan = (token: string) => apiFetch<PlanResponse>('/billing/plan', { token });

export const getPeerBenchmark = (token: string) =>
  apiFetch<PeerBenchmarkResponse>('/benchmark/peer', { token });

// -- Settings ---------------------------------------------------------------

export const getProject = (token: string, projectId: string) =>
  apiFetch<ProjectResponse>(`/projects/${projectId}`, { token });

export const updateSettings = (
  token: string,
  projectId: string,
  body: Schemas['ProjectSettingsRequest'],
) => apiFetch<ProjectResponse>(`/projects/${projectId}/settings`, { method: 'PUT', token, body });

export const listProxyKeys = (token: string, projectId: string) =>
  apiFetch<ProxyKeyResponse[]>(`/projects/${projectId}/proxy-keys`, { token });

export const createProxyKey = (token: string, projectId: string, name: string) =>
  apiFetch<CreatedProxyKeyResponse>(`/projects/${projectId}/proxy-keys`, {
    method: 'POST',
    token,
    body: { name },
  });

export const revokeProxyKey = (token: string, keyId: string) =>
  apiFetch<void>(`/proxy-keys/${keyId}`, { method: 'DELETE', token });

export const testConnection = (token: string, projectId: string, model?: string) =>
  apiFetch<TestConnectionResponse>(`/projects/${projectId}/test-connection`, {
    method: 'POST',
    token,
    body: model ? { model } : {},
  });
