/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/advisor/breakeven": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Breakeven
         * @description Self-hosting vs pay-per-token at this project's real volume — UC-36.
         *
         *     The caveats travel in the payload rather than living in the UI. A bare
         *     "self-hosting is cheaper" is a misleading recommendation (BUILD_SPEC §6.7),
         *     and a caveat the frontend can forget to render is a caveat that will be
         *     forgotten.
         */
        get: operations["breakeven_advisor_breakeven_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/compress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compress
         * @description Analyse a prompt and return a trimmed candidate — UC-26, UC-27.
         *
         *     Takes the body rather than a stored request id, deliberately. Raw prompts
         *     are not stored unless the project opted in (hard rule 9), so a
         *     id-based endpoint would work for some users and not others, and the ones it
         *     failed for would be the privacy-conscious ones. This works for everybody and
         *     stores nothing.
         */
        post: operations["compress_advisor_compress_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/prompt-optimizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Prompt Optimizations
         * @description Prompt and context optimisation opportunities — UC-26, UC-28.
         *
         *     Reads the flags the proxy recorded, not prompts. A project that never opted
         *     into storing raw content gets exactly the same report.
         *
         *     UC-27's *suggestion* is a separate POST: generating a compressed candidate
         *     needs the prompt itself, and we do not store prompts (hard rule 9), so it
         *     cannot be served from a GET over history.
         */
        get: operations["prompt_optimizations_advisor_prompt_optimizations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Recommendations
         * @description Recommendations for a project, largest projected saving first — UC-35, UC-37.
         */
        get: operations["list_recommendations_advisor_recommendations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/advisor/recommendations/{recommendation_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Recommendation Status
         * @description Adopt or dismiss. A dismissed recommendation is never re-suggested.
         */
        post: operations["set_recommendation_status_advisor_recommendations__recommendation_id__status_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Alert history, newest first — UC-34.
         */
        get: operations["list_alerts_alert_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alert-events/{alert_id}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Resolve Alert
         * @description Record what the user did about an alert (UC-34).
         *
         *     The resolution note is the part worth keeping. "Was this real, and what did
         *     we do" is the question a user asks of an alert history six weeks later, and
         *     a status flag alone cannot answer it.
         */
        post: operations["resolve_alert_alert_events__alert_id__resolve_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Exchange credentials for a token pair.
         */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revoke the presented token's whole family.
         *
         *     Succeeds even for an unknown token: logout must never be a way to probe
         *     which tokens exist, and a client trying to log out should never be stuck.
         */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Me
         * @description The authenticated account.
         */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Rotate a refresh token.
         *
         *     Reuse of a consumed token revokes the entire family.
         */
        post: operations["refresh_token_auth_refresh_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Signup
         * @description Create an account and log in.
         *
         *     A duplicate email returns 409, which does disclose that an account exists.
         *     For a developer tool where the alternative is a confusing silent success,
         *     that tradeoff is the right one; the mitigation is rate limiting, not
         *     ambiguity.
         */
        post: operations["signup_auth_signup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/benchmark/peer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Peer Benchmark */
        get: operations["peer_benchmark_benchmark_peer_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Budgets */
        get: operations["list_budgets_budgets_get"];
        put?: never;
        /** Create Budget */
        post: operations["create_budget_budgets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/budgets/{budget_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Budget */
        delete: operations["delete_budget_budgets__budget_id__delete"];
        options?: never;
        head?: never;
        /** Update Budget */
        patch: operations["update_budget_budgets__budget_id__patch"];
        trace?: never;
    };
    "/cache/invalidate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invalidate
         * @description Clear a project's cache — UC-23.
         *
         *     For when something upstream changed — a prompt template, a system prompt —
         *     and stale answers would now be wrong. Clears the Postgres rows and the
         *     Redis exact-match index together; leaving either behind would keep serving
         *     the answers the user just asked us to forget.
         */
        post: operations["invalidate_cache_invalidate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/cache/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cache Stats
         * @description Hit rate, dollars saved, and hits over time — UC-25.
         */
        get: operations["cache_stats_cache_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Liveness: is the process up and serving?
         *
         *     Deliberately checks no dependencies. A liveness probe that fails when
         *     Postgres blips would have the orchestrator restart a perfectly healthy
         *     proxy in the middle of an incident.
         */
        get: operations["healthz_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Keys
         * @description List stored provider keys, metadata only.
         */
        get: operations["list_keys_keys_get"];
        put?: never;
        /**
         * Add Key
         * @description Store a provider key.
         *
         *     Encryption happens before this handler returns, and the plaintext is never
         *     written anywhere (CLAUDE.md hard rule 4).
         */
        post: operations["add_key_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Key
         * @description Remove a provider key (UC-03).
         *
         *     Hard delete, not a flag: the ciphertext has no further purpose, and the
         *     least risky place for a former credential is nowhere.
         */
        delete: operations["delete_key_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Create a project with defaults from BUILD_SPEC §7.
         */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_projects__project_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/kill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Kill Project
         * @description Revoke every proxy key for a project, immediately (UC-33).
         *
         *     Must take effect in under a second (BUILD_SPEC §4 P6), which rules out
         *     waiting for the 60 s auth cache to expire — so the revocation and the cache
         *     purge happen together, and the purge is what actually makes it instant.
         *
         *     Provider keys are deliberately untouched. The user is containing a leak of
         *     *our* credential; destroying their OpenAI key as well would turn one
         *     incident into two, and it is not ours to destroy.
         */
        post: operations["kill_project_projects__project_id__kill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/proxy-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Proxy Keys */
        get: operations["list_proxy_keys_projects__project_id__proxy_keys_get"];
        put?: never;
        /**
         * Create Proxy Key
         * @description Issue a proxy key for a project. The raw key is shown once.
         */
        post: operations["create_proxy_key_projects__project_id__proxy_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Settings
         * @description Partial update of a project's toggles and thresholds.
         */
        put: operations["update_settings_projects__project_id__settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/test-connection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Test Connection
         * @description Send a real, minimal completion and report what happened.
         */
        post: operations["test_connection_projects__project_id__test_connection_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/proxy-keys/{key_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke Proxy Key
         * @description Revoke a proxy key immediately (UC-07).
         *
         *     Scoped to the caller's own keys, so revoking one project's key cannot
         *     affect another user's — or another project's — access.
         */
        delete: operations["revoke_proxy_key_proxy_keys__key_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Readiness: are Postgres and Redis both reachable?
         *
         *     Both probes run concurrently and each is bounded by
         *     ``readiness_timeout_seconds``, so the endpoint cannot hang.
         */
        get: operations["readyz_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description The decision log, newest first, keyset-paginated.
         */
        get: operations["list_requests_requests_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request
         * @description One request, for the detail drawer — UC-12, UC-16.
         */
        get: operations["get_request_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routing-rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rules */
        get: operations["list_rules_routing_rules_get"];
        put?: never;
        /**
         * Create Rule
         * @description Create an override or exclude rule — UC-15, UC-19.
         */
        post: operations["create_rule_routing_rules_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routing-rules/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Rule */
        delete: operations["delete_rule_routing_rules__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/routing/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Routing Stats
         * @description Routing savings, reported separately from caching — UC-18.
         */
        get: operations["routing_stats_routing_stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unsubscribe/{token}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Unsubscribe
         * @description One click, no session, no JavaScript — UC-38.
         *
         *     Unauthenticated by necessity: the link is opened from a mail client months
         *     after the fact, and an unsubscribe that requires logging in is one people
         *     report as spam instead. The token is a 256-bit CSPRNG value and is the only
         *     thing it can act on.
         */
        get: operations["unsubscribe_unsubscribe__token__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Usage
         * @description Spend over time — UC-08.
         */
        get: operations["get_usage_usage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/breakdown": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Breakdown
         * @description Spend split by model, project, endpoint, or provider — UC-09, UC-10, UC-28.
         *
         *     ``avg_tokens`` is what UC-28 ranks endpoints by, so prompt optimization
         *     effort lands where it pays.
         */
        get: operations["get_breakdown_usage_breakdown_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Csv
         * @description Streaming CSV export — UC-13.
         *
         *     Streamed rather than assembled: an export can cover a million rows, and
         *     building that in memory would take the API process down.
         */
        get: operations["export_csv_usage_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/usage/token-distribution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Token Distribution
         * @description Histogram of request sizes — UC-11.
         */
        get: operations["get_token_distribution_usage_token_distribution_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddKeyRequest */
        AddKeyRequest: {
            /** Api Key */
            api_key: string;
            /**
             * Provider
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini";
        };
        /**
         * AlertPage
         * @description Cursor-paginated, per the §8 convention.
         *
         *     `alert_events` is the only table here that grows without bound — budgets
         *     are capped at one per period per project and recommendations are replaced
         *     nightly, so both are bounded by construction and return plain lists. This
         *     one is a history, and a year-old incident is still a row. See ADR 0009.
         */
        AlertPage: {
            /** Alerts */
            alerts: components["schemas"]["AlertResponse"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** AlertResponse */
        AlertResponse: {
            /** Alert Type */
            alert_type: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Id */
            id: string;
            /** Notified At */
            notified_at: string | null;
            /** Project Id */
            project_id: string;
            /** Resolution */
            resolution: string | null;
            /** Resolved At */
            resolved_at: string | null;
            /** Severity */
            severity: string;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** BreakEvenResponse */
        BreakEvenResponse: {
            /** Api Monthly Cost Usd */
            api_monthly_cost_usd: number;
            /** Break Even Tokens */
            break_even_tokens: number | null;
            /** Capacity Tokens Per Gpu */
            capacity_tokens_per_gpu: number;
            /** Caveats */
            caveats: string[];
            /** Gpu Monthly Cost Usd */
            gpu_monthly_cost_usd: number;
            /** Gpu Option */
            gpu_option: string;
            /** Monthly Saving Usd */
            monthly_saving_usd: number;
            /** Monthly Tokens */
            monthly_tokens: number;
            /** N Gpus */
            n_gpus: number;
            /** Options */
            options: {
                [key: string]: unknown;
            }[];
            /** Recommendation */
            recommendation: string;
        };
        /** BreakdownResponse */
        BreakdownResponse: {
            /** By */
            by: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Rows */
            rows: components["schemas"]["BreakdownRow"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** BreakdownRow */
        BreakdownRow: {
            /** Avg Tokens */
            avg_tokens: number;
            /** Cost Usd */
            cost_usd: string;
            /** Key */
            key: string;
            /** Requests */
            requests: number;
            /** Share */
            share: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** BudgetResponse */
        BudgetResponse: {
            /** Action */
            action: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Fraction Used */
            fraction_used: number;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Limit Usd */
            limit_usd: string;
            /** Period */
            period: string;
            /** Project Id */
            project_id: string;
            /** Spent Usd */
            spent_usd: number;
        };
        /** CachePoint */
        CachePoint: {
            /**
             * Day
             * Format: date-time
             */
            day: string;
            /** Hits */
            hits: number;
            /** Requests */
            requests: number;
            /** Savings Usd */
            savings_usd: string;
        };
        /** CacheStatsResponse */
        CacheStatsResponse: {
            /** Avg Hits Per Entry */
            avg_hits_per_entry: number;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Entries */
            entries: number;
            /** Hit Rate */
            hit_rate: number;
            /** Hits */
            hits: number;
            /** Live Entries */
            live_entries: number;
            /** Requests */
            requests: number;
            /** Savings Usd */
            savings_usd: string;
            /** Series */
            series: components["schemas"]["CachePoint"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** CompressRequest */
        CompressRequest: {
            /**
             * Body
             * @description The request body you would send, verbatim.
             */
            body: {
                [key: string]: unknown;
            };
            /** Relevance Threshold */
            relevance_threshold?: number | null;
            /** Token Threshold */
            token_threshold?: number | null;
        };
        /** CompressResponse */
        CompressResponse: {
            /** Message Count */
            message_count: number;
            /** Reason */
            reason: string;
            /** Reclaimable Fraction */
            reclaimable_fraction: number;
            /** Reclaimable Tokens */
            reclaimable_tokens: number;
            /** Stale */
            stale: components["schemas"]["StaleMessageOut"][];
            /** Suggestion */
            suggestion?: {
                [key: string]: unknown;
            } | null;
            /** Total Tokens */
            total_tokens: number;
            /** Warn */
            warn: boolean;
        };
        /** ContextWarningRow */
        ContextWarningRow: {
            /** Avg Message Count */
            avg_message_count: number;
            /** Avg Reclaimable Tokens */
            avg_reclaimable_tokens: number;
            /** Endpoint */
            endpoint: string;
            /** Estimated Wasted Usd */
            estimated_wasted_usd: number;
            /** Requests */
            requests: number;
            /** Warned Requests */
            warned_requests: number;
        };
        /** CreateBudgetRequest */
        CreateBudgetRequest: {
            /**
             * Action
             * @default alert_only
             * @enum {string}
             */
            action: "alert_only" | "soft_throttle" | "hard_stop";
            /** Limit Usd */
            limit_usd: number | string;
            /**
             * Period
             * @enum {string}
             */
            period: "daily" | "weekly" | "monthly";
            /** Project Id */
            project_id: string;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
        };
        /** CreateProxyKeyRequest */
        CreateProxyKeyRequest: {
            /** Name */
            name?: string | null;
        };
        /** CreateRuleRequest */
        CreateRuleRequest: {
            /** Match Condition */
            match_condition?: {
                [key: string]: unknown;
            };
            /**
             * Priority
             * @default 0
             */
            priority: number;
            /** Project Id */
            project_id: string;
            /**
             * Rule Type
             * @enum {string}
             */
            rule_type: "override" | "exclude";
            /** Target Model */
            target_model?: string | null;
        };
        /**
         * CreatedProxyKeyResponse
         * @description Creation response only.
         *
         *     ``key`` is the single time the raw value exists outside the caller's
         *     machine. It is absent from every other response model in this file.
         */
        CreatedProxyKeyResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Key */
            key: string;
            /** Last4 */
            last4: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string | null;
            /** Project Id */
            project_id: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** DismissRequest */
        DismissRequest: {
            /**
             * Status
             * @default dismissed
             */
            status: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HistogramBucket */
        HistogramBucket: {
            /** Cost Usd */
            cost_usd: string;
            /** Label */
            label: string;
            /** Lower */
            lower: number;
            /** Requests */
            requests: number;
            /** Upper */
            upper: number | null;
        };
        /** InvalidateRequest */
        InvalidateRequest: {
            /** Project Id */
            project_id: string;
        };
        /** InvalidateResponse */
        InvalidateResponse: {
            /** Entries Removed */
            entries_removed: number;
            /** Project Id */
            project_id: string;
        };
        /**
         * KeyResponse
         * @description Everything the API will ever say about a stored provider key.
         *
         *     Exactly the fields BUILD_SPEC §4 P1 permits: "and nothing else".
         */
        KeyResponse: {
            /**
             * Added At
             * Format: date-time
             */
            added_at: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last4 */
            last4: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Provider */
            provider: string;
        };
        /** KillSwitchResponse */
        KillSwitchResponse: {
            /** Alert Id */
            alert_id: string | null;
            /** Keys Revoked */
            keys_revoked: number;
            /** Project Id */
            project_id: string;
            /** Took Ms */
            took_ms: number;
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** PeerBenchmarkResponse */
        PeerBenchmarkResponse: {
            /** Available */
            available: boolean;
            /** Cohort P25 */
            cohort_p25: number;
            /** Cohort P50 */
            cohort_p50: number;
            /** Cohort P75 */
            cohort_p75: number;
            /** Cohort Size */
            cohort_size: number;
            /** Minimum Cohort Size */
            minimum_cohort_size: number;
            /** Percentile Band */
            percentile_band: string;
            /** Reason */
            reason: string;
            /** Verdict */
            verdict: string;
            /** Your Cost Per Request */
            your_cost_per_request: number;
            /** Your Requests */
            your_requests: number;
        };
        /** ProjectResponse */
        ProjectResponse: {
            /** Archived At */
            archived_at: string | null;
            /** Cache Enabled */
            cache_enabled: boolean;
            /** Cache Ttl Seconds */
            cache_ttl_seconds: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Escalation Enabled */
            escalation_enabled: boolean;
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Routing Enabled */
            routing_enabled: boolean;
            /** Similarity Threshold */
            similarity_threshold: number;
            /** Store Raw Content */
            store_raw_content: boolean;
        };
        /**
         * ProjectSettingsRequest
         * @description Every field optional — this is a partial update.
         */
        ProjectSettingsRequest: {
            /** Cache Enabled */
            cache_enabled?: boolean | null;
            /** Cache Ttl Seconds */
            cache_ttl_seconds?: number | null;
            /** Escalation Enabled */
            escalation_enabled?: boolean | null;
            /** Name */
            name?: string | null;
            /** Routing Enabled */
            routing_enabled?: boolean | null;
            /** Similarity Threshold */
            similarity_threshold?: number | null;
            /** Store Raw Content */
            store_raw_content?: boolean | null;
        };
        /**
         * PromptOptimizationReport
         * @description UC-26, UC-27 and UC-28 in one payload, per BUILD_SPEC §8.
         *
         *     The two halves belong together: knowing an endpoint is token-heavy is only
         *     actionable once you also know how much of those tokens is stale history.
         *     Split across two endpoints, a dashboard would have to join them to say
         *     anything useful.
         */
        PromptOptimizationReport: {
            /** By Endpoint */
            by_endpoint: components["schemas"]["ContextWarningRow"][];
            /** Estimated Wasted Usd */
            estimated_wasted_usd: number;
            /** Token Heavy */
            token_heavy: components["schemas"]["TokenHeavyRow"][];
            /** Total Requests */
            total_requests: number;
            /** Warned Fraction */
            warned_fraction: number;
            /** Warned Requests */
            warned_requests: number;
        };
        /** ProxyKeyResponse */
        ProxyKeyResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Last4 */
            last4: string;
            /** Last Used At */
            last_used_at: string | null;
            /** Name */
            name: string | null;
            /** Project Id */
            project_id: string;
            /** Revoked At */
            revoked_at: string | null;
        };
        /** RecommendationResponse */
        RecommendationResponse: {
            /** Confidence */
            confidence: string;
            /** Detail */
            detail: {
                [key: string]: unknown;
            };
            /** Generated At */
            generated_at: unknown;
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Projected Savings Usd */
            projected_savings_usd: number;
            /** Sample Size */
            sample_size: number;
            /** Status */
            status: string;
            /** Title */
            title: string;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** RequestPage */
        RequestPage: {
            /** Has More */
            has_more: boolean;
            /** Next Cursor */
            next_cursor: string | null;
            /** Rows */
            rows: components["schemas"]["RequestRow"][];
        };
        /** RequestRow */
        RequestRow: {
            /** Cache Hit */
            cache_hit: boolean;
            /** Cache Similarity */
            cache_similarity: number | null;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Would Have Been Usd */
            cost_would_have_been_usd: string | null;
            /**
             * Decision
             * @enum {string}
             */
            decision: "cache_hit" | "routed" | "passthrough" | "escalated" | "error";
            /** Endpoint */
            endpoint: string;
            /** Error Code */
            error_code: string | null;
            /** Escalation Triggered */
            escalation_triggered: boolean;
            /** Id */
            id: string;
            /** Latency Ms */
            latency_ms: number;
            /** Model Requested */
            model_requested: string;
            /** Model Used */
            model_used: string;
            /** Project Id */
            project_id: string;
            /** Provider */
            provider: string;
            /** Request Id */
            request_id: string;
            /** Routed */
            routed: boolean;
            /** Routing Reason Code */
            routing_reason_code: string | null;
            /** Saved Usd */
            saved_usd: string;
            /** Status */
            status: number;
            /** Streamed */
            streamed: boolean;
            /**
             * Timestamp
             * Format: date-time
             */
            timestamp: string;
            /** Tokens Estimated */
            tokens_estimated: boolean;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
            /** Ttft Ms */
            ttft_ms: number | null;
        };
        /** ResolveAlertRequest */
        ResolveAlertRequest: {
            /** Resolution */
            resolution?: string | null;
            /**
             * Status
             * @default resolved
             * @enum {string}
             */
            status: "acknowledged" | "resolved";
        };
        /** RoutingStatsResponse */
        RoutingStatsResponse: {
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Escalation Cost Usd */
            escalation_cost_usd: string;
            /** Escalation Rate */
            escalation_rate: number;
            /** Escalations */
            escalations: number;
            /** Gross Savings Usd */
            gross_savings_usd: string;
            /** Passthrough Requests */
            passthrough_requests: number;
            /** Routed Requests */
            routed_requests: number;
            /** Savings Usd */
            savings_usd: string;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** Tier Distribution */
            tier_distribution: components["schemas"]["TierRow"][];
        };
        /** RuleResponse */
        RuleResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Id */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Match Condition */
            match_condition: {
                [key: string]: unknown;
            };
            /** Priority */
            priority: number;
            /** Project Id */
            project_id: string;
            /** Rule Type */
            rule_type: string;
            /** Target Model */
            target_model: string | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
        };
        /** StaleMessageOut */
        StaleMessageOut: {
            /** Index */
            index: number;
            /** Relevance */
            relevance: number;
            /** Role */
            role: string;
            /** Tokens */
            tokens: number;
        };
        /** TestConnectionRequest */
        TestConnectionRequest: {
            /**
             * Model
             * @default gpt-4o-mini
             */
            model: string;
            /**
             * Provider
             * @default openai
             * @enum {string}
             */
            provider: "openai" | "anthropic" | "gemini";
        };
        /** TestConnectionResponse */
        TestConnectionResponse: {
            /** Latency Ms */
            latency_ms?: number | null;
            /** Message */
            message: string;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
            /** Provider */
            provider: string;
            /** Reason */
            reason?: ("no_provider_key" | "no_proxy_key" | "provider_key_rejected" | "provider_unreachable" | "provider_error" | "key_decrypt_failed" | "model_unavailable") | null;
            /** Tokens Used */
            tokens_used?: number | null;
        };
        /** TierRow */
        TierRow: {
            /** Model */
            model: string;
            /** Requests */
            requests: number;
            /** Share */
            share: number;
        };
        /** TokenDistributionResponse */
        TokenDistributionResponse: {
            /** Buckets */
            buckets: components["schemas"]["HistogramBucket"][];
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Median Tokens Bucket */
            median_tokens_bucket: number;
            /** P95 Tokens Bucket */
            p95_tokens_bucket: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
        };
        /** TokenHeavyRow */
        TokenHeavyRow: {
            /** Avg Tokens In */
            avg_tokens_in: number;
            /** Avg Tokens Out */
            avg_tokens_out: number;
            /** Avg Tokens Total */
            avg_tokens_total: number;
            /** Endpoint */
            endpoint: string;
            /** Requests */
            requests: number;
            /** Total Cost Usd */
            total_cost_usd: number;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UpdateBudgetRequest */
        UpdateBudgetRequest: {
            /** Action */
            action?: ("alert_only" | "soft_throttle" | "hard_stop") | null;
            /** Is Active */
            is_active?: boolean | null;
            /** Limit Usd */
            limit_usd?: number | string | null;
        };
        /** UsagePoint */
        UsagePoint: {
            /**
             * Bucket
             * Format: date-time
             */
            bucket: string;
            /** Cache Hits */
            cache_hits: number;
            /** Cost Usd */
            cost_usd: string;
            /** Cost Would Have Been Usd */
            cost_would_have_been_usd: string;
            /** Requests */
            requests: number;
            /** Tokens In */
            tokens_in: number;
            /** Tokens Out */
            tokens_out: number;
        };
        /** UsageResponse */
        UsageResponse: {
            /** Bucket */
            bucket: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Range */
            range: string;
            /** Series */
            series: components["schemas"]["UsagePoint"][];
            /**
             * Start
             * Format: date-time
             */
            start: string;
            summary: components["schemas"]["UsageSummary"];
        };
        /**
         * UsageSummary
         * @description Totals for the window, plus the savings split by mechanism.
         *
         *     Caching and routing savings are computed separately and never
         *     double-counted — a cache hit is not also a routing win (CODEBASE_GUIDE §6).
         */
        UsageSummary: {
            /** Cache Hit Rate */
            cache_hit_rate: number;
            /** Cache Hits */
            cache_hits: number;
            /** Cache Savings Usd */
            cache_savings_usd: string;
            /** Routing Savings Usd */
            routing_savings_usd: string;
            /** Total Cost Usd */
            total_cost_usd: string;
            /** Total Requests */
            total_requests: number;
            /** Total Tokens In */
            total_tokens_in: number;
            /** Total Tokens Out */
            total_tokens_out: number;
            /** Total Would Have Been Usd */
            total_would_have_been_usd: string;
        };
        /** UserResponse */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Id */
            id: string;
            /** Plan Id */
            plan_id: string;
            /** Timezone */
            timezone: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    breakeven_advisor_breakeven_get: {
        parameters: {
            query: {
                project_id: string;
                gpu?: string | null;
                utilization?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakEvenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compress_advisor_compress_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompressRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompressResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prompt_optimizations_advisor_prompt_optimizations_get: {
        parameters: {
            query: {
                project_id: string;
                range?: "today" | "7d" | "30d" | "90d" | "custom";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PromptOptimizationReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_recommendations_advisor_recommendations_get: {
        parameters: {
            query: {
                project_id: string;
                include_dismissed?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_recommendation_status_advisor_recommendations__recommendation_id__status_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recommendation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DismissRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_alert_events_get: {
        parameters: {
            query?: {
                project_id?: string | null;
                status?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    resolve_alert_alert_events__alert_id__resolve_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResolveAlertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    refresh_token_auth_refresh_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signup_auth_signup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    peer_benchmark_benchmark_peer_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PeerBenchmarkResponse"];
                };
            };
        };
    };
    list_budgets_budgets_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_budget_budgets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_budget_budgets__budget_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_budget_budgets__budget_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                budget_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBudgetRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BudgetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    invalidate_cache_invalidate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvalidateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvalidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cache_stats_cache_stats_get: {
        parameters: {
            query?: {
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CacheStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_keys_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyResponse"][];
                };
            };
        };
    };
    add_key_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_key_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"][];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kill_project_projects__project_id__kill_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KillSwitchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_proxy_keys_projects__project_id__proxy_keys_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyKeyResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_proxy_key_projects__project_id__proxy_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProxyKeyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreatedProxyKeyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_settings_projects__project_id__settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSettingsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_connection_projects__project_id__test_connection_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TestConnectionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestConnectionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    revoke_proxy_key_proxy_keys__key_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    readyz_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
                project_id?: string | null;
                model?: string | null;
                decision?: ("cache_hit" | "routed" | "passthrough" | "escalated" | "error") | null;
                status_min?: number | null;
                search?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RequestRow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rules_routing_rules_get: {
        parameters: {
            query?: {
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rule_routing_rules_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRuleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RuleResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_rule_routing_rules__rule_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    routing_stats_routing_stats_get: {
        parameters: {
            query?: {
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoutingStatsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unsubscribe_unsubscribe__token__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                token: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_usage_usage_get: {
        parameters: {
            query?: {
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UsageResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_breakdown_usage_breakdown_get: {
        parameters: {
            query?: {
                by?: "model" | "project" | "endpoint" | "provider";
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BreakdownResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_csv_usage_export_csv_get: {
        parameters: {
            query?: {
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_token_distribution_usage_token_distribution_get: {
        parameters: {
            query?: {
                range?: "today" | "7d" | "30d" | "90d" | "custom";
                project_id?: string | null;
                start?: string | null;
                end?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenDistributionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
