"""Capability-tier classifier — BUILD_SPEC §4 P5.

Logistic regression over :mod:`apicost.routing.features`, predicting the tier a
request actually needs (``cheap | mid | strong``) with a calibrated
probability. Loaded from a joblib artifact at startup, swappable without a
redeploy, and versioned — ``model_version`` is recorded on every routed request
so a bad artifact can be traced to the rows it affected.

Two properties matter more than accuracy:

* **It must be fast.** Single-digit milliseconds; the pipeline gives it 20 ms
  and treats an overrun as a failure.
* **It must never raise.** :func:`predict` returns ``None`` on any problem, and
  ``None`` means passthrough to the model the caller asked for.

The confidence calibration is weak until there is real escalation-outcome data
to retrain on (CODEBASE_GUIDE §13), so the default threshold is deliberately
conservative — we would rather route too little than degrade someone's output.
"""

from __future__ import annotations

import threading
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Final, Literal

from apicost.core.logging import get_logger
from apicost.routing.features import FEATURE_NAMES, PromptFeatures, to_vector

__all__ = [
    "DEFAULT_MIN_CONFIDENCE",
    "Tier",
    "TierPrediction",
    "artifact_path",
    "classifier_is_ready",
    "load_classifier",
    "predict",
    "unload_classifier",
    "warm_classifier",
]

Tier = Literal["cheap", "mid", "strong"]
TIERS: Final[tuple[Tier, ...]] = ("cheap", "mid", "strong")

DEFAULT_MIN_CONFIDENCE: Final = 0.70
"""Below this the prediction is not acted on. Conservative on purpose: the
classifier is trained on a small seed set and its calibration is not yet
trustworthy, and the cost of routing a hard request to a weak model is a bad
answer in somebody's product."""

MODEL_VERSION_UNKNOWN: Final = "unloaded"

_logger = get_logger(__name__)

_model: Any | None = None
_version: str = MODEL_VERSION_UNKNOWN
_lock = threading.Lock()
_load_failed = False


@dataclass(frozen=True)
class TierPrediction:
    tier: Tier
    confidence: float
    model_version: str


def artifact_path() -> Path:
    """Where the trained artifact lives.

    Beside the package rather than in it: the artifact is data, it is
    regenerated by ``routing/train.py``, and it should be replaceable without
    touching an installed wheel.
    """
    return Path(__file__).resolve().parent / "artifacts" / "tier_classifier.joblib"


def load_classifier(path: Path | None = None) -> bool:
    """Load the artifact. Returns whether a usable model is present."""
    global _model, _version, _load_failed

    target = path or artifact_path()

    with _lock:
        if _model is not None:
            return True
        if _load_failed and path is None:
            return False

        if not target.exists():
            _load_failed = True
            _logger.info(
                "routing_classifier_absent",
                path=str(target),
                detail="routing will pass through until an artifact is trained",
            )
            return False

        try:
            import joblib

            bundle = joblib.load(target)
            model = bundle["model"]
            feature_names = tuple(bundle.get("feature_names", ()))

            if feature_names != FEATURE_NAMES:
                # Training and serving disagree about what the columns mean.
                # Using it anyway would produce confident nonsense.
                _load_failed = True
                _logger.warning(
                    "routing_classifier_feature_mismatch",
                    expected=len(FEATURE_NAMES),
                    found=len(feature_names),
                )
                return False

            _model = model
            _version = str(bundle.get("version", "unknown"))
            _logger.info("routing_classifier_loaded", version=_version)
            return True
        except Exception:
            _load_failed = True
            _logger.warning("routing_classifier_load_failed", exc_info=True)
            return False


def warm_classifier() -> bool:
    """Load the artifact and run one prediction through it.

    Loading alone is not enough: sklearn does lazy allocation on the first
    ``predict_proba``, so a load-only startup leaves that cost for whichever
    request arrives first — and this path has a 20 ms budget it would blow.
    """
    if not load_classifier():
        return False

    from apicost.routing.features import extract_features

    predict(
        extract_features({"model": "gpt-4o", "messages": [{"role": "user", "content": "warmup"}]})
    )
    return True


def classifier_is_ready() -> bool:
    return _model is not None


def unload_classifier() -> None:
    """Drop the model. For tests and for swapping an artifact."""
    global _model, _version, _load_failed
    with _lock:
        _model = None
        _version = MODEL_VERSION_UNKNOWN
        _load_failed = False


def predict(features: PromptFeatures) -> TierPrediction | None:
    """Predict the required tier, or ``None``.

    ``None`` means "no opinion" and the caller should pass through. Never
    raises: a classifier that throws must not become a failed request.
    """
    model = _model
    if model is None:
        return None

    try:
        vector = [to_vector(features)]
        probabilities = model.predict_proba(vector)[0]
        best = int(max(range(len(probabilities)), key=lambda i: probabilities[i]))

        classes = list(getattr(model, "classes_", TIERS))
        tier = str(classes[best])
        if tier not in TIERS:
            return None

        return TierPrediction(
            tier=tier,
            confidence=float(probabilities[best]),
            model_version=_version,
        )
    except Exception:
        _logger.warning("routing_classifier_predict_failed", exc_info=True)
        return None
